//
// Created by tim on 5/23/26.
//

#ifndef VOXELENGINEMESHBASED_DIRECTION_H
#define VOXELENGINEMESHBASED_DIRECTION_H

enum Direction {
    RIGHT, LEFT, UP, DOWN, FORWARD, BACKWARD
};

#endif //VOXELENGINEMESHBASED_DIRECTION_H